spring:
  datasource:
    url: jdbc:mysql://101.35.200.75:3306/team_assessment?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 34d90879740311bb

logging:
  config: classpath:logback-spring.xml
  level:
    com.team.assessment: info

WeChat:
  appid: wxa7559ae265298124
  secret: e125e80e8a6dc124a1aaefc16e7e1368