spring:
  datasource:
    url: jdbc:mysql://101.35.200.75:3306/team_assessment?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 9dd5237efb33fbb2

#logging:
#  config: classpath:logback-spring.xml
#  level:
#    com.trade.training: debug
## swagger
#swagger:
#  enable: true
WeChat:
  appid: wxa7559ae265298124
  secret: e125e80e8a6dc124a1aaefc16e7e1368