spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/team_assessment?allowMultiQueries=true&useUnicode=true&useSSL=false&characterEncoding=UTF-8
    username: root
    password: 9dd5237efb33fbb2

logging:
  config: classpath:logback-spring.xml
  level:
    com.trade.training: info

swagger:
  enable: false